### ISSUE TITLE
Counter-Phisher v3.0.0 Update

### ISSUE THREAD

**Issue by Rarixty** [EwyBoy/Counter-Phishing-Tool#5]
Hello, i need update for the latest types of phishing are even more dangerous, please update to support today's phishing. Thank you!

**Comment by spinfal** [comment]
@Rarixty can you please elaborate more about what you mean by "today's phishing"? being a bit more specific helps out the maintainers and people who wish to contribute via PRs :-)

**Comment by Demopans** [comment]
Likely something that has to do with extra fields that are required by the other end of whatever API used by phishers. It shouldn't be nontrivial to hardcode extra fields but you should update the README so people know at least

**Comment by EwyBoy** [comment]
I originally made this 6 years ago and have not really updated it since then.
But as a response to this, I made some huge changes to the script/program. This will be version 3.0.0 and will now instead contain a form data file named `form_data.json` where you can simply paste in your captured form data payload and modify it to your needs.

```json
{
  "foo": 69,
  "email": "@RANDOM_EMAIL",
  "password": "@RANDOM_PASSWORD",
  "bar": false
}
```

I have created a bunch of built in replaceable that will replace the @RANDOM_XYZ with randomly generated fake data.

Added fields:
- `@RANDOM_PASSWORD`: Generates a random password.
- `@RANDOM_EMAIL`: Generates a random email address.
- `@RANDOM_NUMBER`: Generates a random number.
- `@RANDOM_DIGIT`: Generates a random digit.
- `@RANDOM_BOOLEAN`: Generates a random boolean.
- `@RANDOM_FULLNAME`: Generates a random full name.
- `@RANDOM_FIRSTNAME`: Generates a random first name.
- `@RANDOM_FIRSTNAME_MALE`: Generates a random male first name.
- `@RANDOM_FIRSTNAME_FEMALE`: Generates random female first name.
- `@RANDOM_SURNAME`: Generates a random surname.
- `@RANDOM_WORD`: Generates a random word.
- `@RANDOM_LETTER`: Generates a random letter.

This way the program should be way more flexible and you will no longer need to hardcode extra fields.
I will continue to work on this new version in the following days to add more random fake data fields such as
- `@RANDOM_DATE`: Generates a random date.
- `@RANDOM_IP`: Generates a random IP address.
- `@RANDOM_COUNTRY`: Generates a random country.
- `@RANDOM_CITY`: Generates a random city.
- `@RANDOM_STREET`: Generates a random street.
- `@RANDOM_ZIP`: Generates a random ZIP code.
- `@RANDOM_PHONE`: Generates a random phone number.
- `@RANDOM_GENDER`: Generates a random
- `@RANDOM_JOB`: Generates a random job.
- `@RANDOM_COMPANY`: Generates a random company.
- `@RANDOM_CREDIT_CARD`: Generates a random credit card number.
- `@RANDOM_CVV`: Generates a random CVV number.
- `@RANDOM_EXPIRY`: Generates a random expiry date.
- `@RANDOM_STATE`: Generates a random state.
- `@RANDOM_SSN`: Generates a random SSN number.
- `@RANDOM_URL`: Generates a random URL.
- `@RANDOM_DOMAIN`: Generates a random domain.
- `@RANDOM_USER_AGENT`: Generates a random user agent.
etc

I will also create automated builds for 
- Windows
- Linux
- Mac

Sounds good?
